//SPDX-License-Identifier: BUSL-1.1
pragma solidity >=0.8.28 <0.9.0;

interface ICoinbase {
    // ================================ //
    //            Constants             //
    // ================================ //
    // Public immutables surfaced via autogenerated getters
    function VAL_ID() external view returns (uint64);
    function SHMONAD() external view returns (address);
    function AUTH_ADDRESS() external view returns (address);

    // ================================ //
    //          Core Function           //
    // ================================ //
    function process() external returns (bool success);

    // ================================ //
    //         onlyAuth Setters         //
    // ================================ //
    function updateCommissionRate(uint256 newCommissionRate) external;
    function updateCommissionRateFromStakingConfig() external;
    function updateCommissionRecipient(address newRecipient) external;

    // ================================ //
    //               Views              //
    // ================================ //
    function getCommissionRate() external view returns (uint256);
    function getCommissionRecipient() external view returns (address);
}
